ds_list_add(global.saveroom, id)
var lay_id = layer_get_id("Tiles_1")
var map_id = layer_tilemap_get_id(lay_id)
var data1 = tilemap_get_at_pixel(map_id, x, y)
var data2 = tilemap_get_at_pixel(map_id, x, (y - 1))
var data3 = tilemap_get_at_pixel(map_id, (x - 1), y)
var data4 = tilemap_get_at_pixel(map_id, (x - 1), (y - 1))
data1 = tile_set_empty(data1)
data2 = tile_set_empty(data2)
data3 = tile_set_empty(data3)
data4 = tile_set_empty(data4)
tilemap_set_at_pixel(map_id, data1, x, y)
tilemap_set_at_pixel(map_id, data2, x, (y - 1))
tilemap_set_at_pixel(map_id, data3, (x - 1), y)
tilemap_set_at_pixel(map_id, data4, (x - 1), (y - 1))
lay_id = layer_get_id("Tiles_1a")
map_id = layer_tilemap_get_id(lay_id)
data1 = tilemap_get_at_pixel(map_id, x, y)
data2 = tilemap_get_at_pixel(map_id, x, (y - 1))
data3 = tilemap_get_at_pixel(map_id, (x - 1), y)
data4 = tilemap_get_at_pixel(map_id, (x - 1), (y - 1))
data1 = tile_set_empty(data1)
data2 = tile_set_empty(data2)
data3 = tile_set_empty(data3)
data4 = tile_set_empty(data4)
tilemap_set_at_pixel(map_id, data1, x, y)
tilemap_set_at_pixel(map_id, data2, x, (y - 1))
tilemap_set_at_pixel(map_id, data3, (x - 1), y)
tilemap_set_at_pixel(map_id, data4, (x - 1), (y - 1))
lay_id = layer_get_id("Tiles_4")
map_id = layer_tilemap_get_id(lay_id)
data1 = tilemap_get_at_pixel(map_id, x, y)
data2 = tilemap_get_at_pixel(map_id, x, (y - 1))
data3 = tilemap_get_at_pixel(map_id, (x - 1), y)
data4 = tilemap_get_at_pixel(map_id, (x - 1), (y - 1))
data1 = tile_set_empty(data1)
data2 = tile_set_empty(data2)
data3 = tile_set_empty(data3)
data4 = tile_set_empty(data4)
tilemap_set_at_pixel(map_id, data1, x, y)
tilemap_set_at_pixel(map_id, data2, x, (y - 1))
tilemap_set_at_pixel(map_id, data3, (x - 1), y)
tilemap_set_at_pixel(map_id, data4, (x - 1), (y - 1))
