select1 = min(select1, 3)
select1 = max(select1, 1)
select2 = min(select2, 6)
select2 = max(select2, 1)
select3 = min(select3, 2)
select3 = max(select3, 1)
manual_select = min(manual_select, 13)
manual_select = max(manual_select, 0)
config_select = min(config_select, 10)
config_select = max(config_select, 1)
vol_gen = min(vol_gen, 100)
vol_gen = max(vol_gen, 0)
vol_mu = min(vol_mu, 100)
vol_mu = max(vol_mu, 0)
vol_sfx = min(vol_sfx, 100)
vol_sfx = max(vol_sfx, 0)
audio_set_master_gain(0, (vol_gen / 100))
audio_group_set_gain(1, (vol_mu / 100), 0)
audio_group_set_gain(2, (vol_sfx / 100), 0)
window_set_fullscreen(fullscreen)
ini_open(global.savedata_ini)
ini_write_real("options", "vol_gen", vol_gen)
ini_write_real("options", "vol_sfx", vol_sfx)
ini_write_real("options", "vol_mu", vol_mu)
ini_write_real("options", "fullscreen", fullscreen)
ini_write_real("config", "key_left", global.key_left)
ini_write_real("config", "key_right", global.key_right)
ini_write_real("config", "key_up", global.key_up)
ini_write_real("config", "key_down", global.key_down)
ini_write_real("config", "key_jump", global.key_jump)
ini_write_real("config", "key_grab", global.key_grab)
ini_write_real("config", "key_taunt", global.key_taunt)
ini_write_real("config", "key_shoot", global.key_shoot)
ini_write_real("config", "key_dash", global.key_dash)
ini_close()
